---
- name: Install ubuntu `:role:base` packages
  package:
    name:
    - autofs
    - bzip2
    - cifs-utils
    - curl
    - gdisk
    - git
    - git-lfs
    - gparted
    - keychain
    - myrepos
    - nfs-common
    - python3-pip
    - python3-venv
    - subversion
    - vim
    - wget
